config/routes.rb
Dwc::Application.routes.draw do
  resources :blogs do
    member do
      put "addcool", to: "blogs#addcool"
    end
  end

  resources :archives

  devise_for :users
  resources :referrers

  root "pages#home"
  get "about" => "pages#about"
  get "recent" => "pages#recent"
  get "invite" => "pages#invite"
  get "shop" => "pages#shop"
  get "thankyou" => "pages#thankyou"

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  resources :charges

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /blogs
  def index
    @blogs = Blog.all.order('created_at DESC')
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    redirect_to blogs_url
  end

  def addcool
    @blog = Blog.find(params[:id])
    @blog.cool += 1
    @blog.save!
    redirect_to request.referrer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :subtitle, :content, :date, :cool)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :content %>
    <%= f.input :date %>
    <%= f.input :cool %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
	<div class="row" style="margin-bottom: 30px;">
		<div class="col-md-8 col-md-offset-2">
			<%= link_to blogs_path do %>
				<i class="fa fa-long-arrow-left"> Back</i>
			<% end %>
			<br />
			<h1>Edit Blog</h1>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/blogs/index.html.erb
<div class="container" style="position: relative;">
  <% if user_signed_in? %>
    <div class="admin-control">
      <%= link_to new_blog_path, class: "fa-stack fa-lg" do %>
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-plus fa-stack-1x fa-inverse"></i>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% @blogs.each do |blog| %>
        <div class="row">
          <div class="col-md-10">    
            <%= blog.date.strftime("%B %e, %Y")  %> 
            <h1><%= link_to blog.title, blog, {:class => "raleway"} %></h1>
            <h4><%= blog.subtitle %></h4>
          </div>
          <div class="col-md-2">
            <div class="center" style="margin-top: 40px;">
              <%= link_to addcool_blog_path(blog), method: :put do %>
                <span class="fa fa-bullseye fa-2x"></span>
                <br />
                <b><%= blog.cool %> COOLS</b>
              <% end %>
            </div>
          </div>
        </div>
        <hr />
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
	<div class="row" style="margin-bottom: 30px;">
		<div class="col-md-8 col-md-offset-2">
			<%= link_to blogs_path do %>
				<i class="fa fa-long-arrow-left"> Back</i>
			<% end %>
			<br />
			<h1>New Blog</h1>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/blogs/show.html.erb
<div class="container" style="position: relative; margin-bottom: 30px;">
	<p id="notice"><%= notice %></p>

	<% if user_signed_in? %>
    <div class="admin-control">
      <%= link_to edit_blog_path(@blog), class: "fa-stack fa-lg" do %>
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
      <% end %>
    </div>
  <% end %>

  <div class="row">
  	<div class="col-md-8 col-md-offset-2">
			<%= link_to blogs_path do %>
				<i class="fa fa-long-arrow-left"> Back</i>
			<% end %>
			<br /><br />

			<%= @blog.date.strftime("%B %e, %Y") %>
			<h1 class="raleway"><%= @blog.title %></h1>
			<h3><%= @blog.subtitle %></h3>


			<p style="margin-top: 60px; font-size: 18px; line-height: 2;">
				<%= @blog.content.html_safe %>
			</p>
			<hr />
			<div class="center">
			  <%= link_to addcool_blog_path(@blog), method: :put do %>
			    <span class="fa fa-bullseye fa-3x"></span>
			    <br />
			    <b><%= @blog.cool %> COOLS</b>
			  <% end %>
			</div>
		</div>
	</div>

</div>