config/routes.rb
Dwc::Application.routes.draw do
  resources :blogs do
    member do
      put "addcool", to: "blogs#addcool"
    end
  end

  resources :archives

  devise_for :users
  resources :referrers

  root "pages#home"
  get "about" => "pages#about"
  get "recent" => "pages#recent"
  get "invite" => "pages#invite"
  get "shop" => "pages#shop"
  get "thankyou" => "pages#thankyou"

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  resources :charges

end

app/models/archive.rb
class Archive < ActiveRecord::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: 'Archive was successfully created.' }
        format.json { render action: 'show', status: :created, location: @archive }
      else
        format.html { render action: 'new' }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: 'Archive was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:date, :title, :code)
    end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/_form.html.erb
<%= simple_form_for(@archive) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :title %>
    <%= f.input :code %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<div class="container">
	<div class="row" style="margin-bottom: 30px;">
		<div class="col-md-8 col-md-offset-2">
			<%= link_to archives_path do %>
				<i class="fa fa-long-arrow-left"> Back</i>
			<% end %>
			<br />
			<h1>Edit Archive</h1>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/archives/index.html.erb
<div class="container" style="position: relative;">
  <% if user_signed_in? %>
    <div class="admin-control">
      <%= link_to new_archive_path, class: "fa-stack fa-lg" do %>
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-plus fa-stack-1x fa-inverse"></i>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% @archives.each do |archive| %>
        <div class="row">
          <div class="col-md-12">    
            <%= archive.date.strftime("%B %e, %Y")  %> 
            <h1><%= link_to archive.title, archive, {:class => "raleway"} %></h1>
          </div>
        </div>
        <hr />
      <% end %>
    </div>
  </div>
  <div class="center">
    <%= will_paginate @archives %>
  </div>
</div>

app/views/archives/new.html.erb
<div class="container">
	<div class="row" style="margin-bottom: 30px;">
		<div class="col-md-8 col-md-offset-2">
			<%= link_to archives_path do %>
				<i class="fa fa-long-arrow-left"> Back</i>
			<% end %>
			<br />
			<h1>New Archive</h1>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/archives/show.html.erb
<div class="container" style="background-color: #fff;">
	<p id="notice"><%= notice %></p>

	<% if user_signed_in? %>
    <div class="admin-control">
      <%= link_to edit_archive_path(@archive), class: "fa-stack fa-lg" do %>
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
      <% end %>
    </div>
  <% end %>

	<div class="row" style="margin-bottom: 15px;">
	<div class="col-md-8 col-md-offset-2">
		<%= link_to archives_path do %>
			<i class="fa fa-long-arrow-left"> Back</i>
		<% end %>
		<br /><br />
		<small class="cabin"><%= @archive.date.strftime("%A %B %e, %Y").upcase %></small>
		<h2 class="cabin" style="text-align: left;"><%= @archive.title.upcase %></h2>
		<br />
		<%= @archive.code.html_safe %>
	</div>
</div>

</div>