config/routes.rb
Dwc::Application.routes.draw do
  resources :blogs do
    member do
      put "addcool", to: "blogs#addcool"
    end
  end

  resources :archives

  devise_for :users
  resources :referrers

  root "pages#home"
  get "about" => "pages#about"
  get "recent" => "pages#recent"
  get "invite" => "pages#invite"
  get "shop" => "pages#shop"
  get "thankyou" => "pages#thankyou"

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  resources :charges

end

app/models/referrer.rb
class Referrer < ActiveRecord::Base

	def self.search(search)
		if search
			where('lower(email) = ?', "#{search}".downcase)
		else
			where('email = ?', "none")
		end
	end
end

app/controllers/referrers_controller.rb
class ReferrersController < ApplicationController
  before_action :set_referrer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: []

  def index
    @referrers = Referrer.all.order(:email)
  end

  def show
  end

  def new
    @referrer = Referrer.new
  end

  def edit
  end

  def create
    @referrer = Referrer.new(referrer_params)

    respond_to do |format|
      if @referrer.save
        format.html { redirect_to @referrer, notice: 'Referrer was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @referrer.update(referrer_params)
        format.html { redirect_to @referrer, notice: 'Referrer was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @referrer.destroy
    respond_to do |format|
      format.html { redirect_to referrers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_referrer
      @referrer = Referrer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def referrer_params
      params.require(:referrer).permit(:email, :referrals, :points, :breakroom)
    end
end

app/helpers/referrers_helper.rb
module ReferrersHelper
end

app/views/referrers/_form.html.erb
<%= simple_form_for(@referrer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :referrals %>
    <%= f.input :points %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/referrers/edit.html.erb
<div class="container">
	<div class="row" style="margin-bottom: 30px;">
		<div class="col-md-8 col-md-offset-2">
			<%= link_to referrers_path do %>
				<i class="fa fa-long-arrow-left"> Back</i>
			<% end %>
			<br />
			<h1>Edit Referrer</h1>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/referrers/index.html.erb
<div class="container" style="position: relative;">
  <% if user_signed_in? %>
    <div class="admin-control">
      <%= link_to new_referrer_path, class: "fa-stack fa-lg" do %>
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-plus fa-stack-1x fa-inverse"></i>
      <% end %>
    </div>
  <% end %>
  <h1>Breakroom Referrers</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Referrals</th>
        <th>Points</th>
        <th>Breakroom</th>
        <th>Last Updated</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @referrers.each do |referrer| %>
        <tr>
          <td><%= link_to referrer.email, referrer %></td>
          <td><%= referrer.referrals %></td>
          <td><%= referrer.points %></td>
          <td>
            <% if referrer.breakroom %>
              <span class="fa fa-check-circle" style="color: #1abc9c;"></span>
            <% else %>
              <span class="fa fa-times-circle" style="color: #e74c3c;"></span>
            <% end %>
          </td>
          <td><%= referrer.updated_at.strftime("%m/%d/%y") %></td>
          <td>
            <%= link_to edit_referrer_path(referrer) do %>
              <span class="fa fa-edit"></span>
              Edit
            <% end %>
          </td>
          <td>
            <%= link_to referrer, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="fa fa-trash-o"></span>
              Delete
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/referrers/new.html.erb
<div class="container">
	<div class="row" style="margin-bottom: 30px;">
		<div class="col-md-8 col-md-offset-2">
			<%= link_to referrers_path do %>
				<i class="fa fa-long-arrow-left"> Back</i>
			<% end %>
			<br />
			<h1>New Referrer</h1>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/referrers/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Email:</strong>
	  <%= @referrer.email %>
	</p>

	<p>
	  <strong>Referrals:</strong>
	  <%= @referrer.referrals %>
	</p>

	<p>
	  <strong>Points:</strong>
	  <%= @referrer.points %>
	</p>

	<p>
	  <strong>Breakroom:</strong>
	  <% if @referrer.breakroom %>
      <span class="fa fa-check-circle" style="color: #1abc9c;"></span>
    <% else %>
      <span class="fa fa-times-circle" style="color: #e74c3c;"></span>
    <% end %>
	</p>

	<%= link_to edit_referrer_path(@referrer) do %>
    <span class="fa fa-edit"></span>
    Edit
  <% end %>
  |
  <%= link_to "Index", referrers_path %>
</div>