config/routes.rb
Dwc::Application.routes.draw do
  resources :blogs do
    member do
      put "addcool", to: "blogs#addcool"
    end
  end

  resources :archives

  devise_for :users
  resources :referrers

  root "pages#home"
  get "about" => "pages#about"
  get "recent" => "pages#recent"
  get "invite" => "pages#invite"
  get "shop" => "pages#shop"
  get "thankyou" => "pages#thankyou"

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  resources :charges

end

app/views/layouts/_footer.html.erb
<div id="">
 	<div class="container center">
 		<div style="margin-top: 60px;">
	 		<%= link_to "https://www.facebook.com/dailywatercooler" do %>
				<i class="fa fa-facebook fa-lg" style="font-size: 24px;"></i>
			<% end %>
			&nbsp; &nbsp;
			<%= link_to "https://twitter.com/the_dwc" do %>
				<i class="fa fa-twitter fa-lg" style="font-size: 24px;"></i>
			<% end %>
			&nbsp; &nbsp;
			<%= link_to "https://instagram.com/the_dwc" do %>
				<i class="fa fa-instagram fa-lg" style="font-size: 24px;"></i>
			<% end %>
		</div>
 		<div class="cabin footer_nav">
			<!--<div class="footer_item"><%= link_to "RECENT ISSUES", recent_path %></div>-->
 			<div class="footer_item"><%= link_to "ABOUT", about_path %></div>
 			<!--<div class="footer_item"><%= link_to "BLOG", blogs_path %></div>-->
			<div class="footer_item"><%= link_to "INVITE", invite_path %></div>
 		</div>
  </div>
</div>


				

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48722911-1', 'the-dwc.co');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		    <span class="sr-only">Toggle navigation</span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		  </button>
		  <%= link_to (image_tag "logo2016.png", :size => "40x40", :title => "The Daily Water Cooler"), root_path, class: "navbar-brand" %>
		</div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav navbar-right cabin" style="letter-spacing: 2px;">
	      <li><%= link_to "INVITE A FRIEND", invite_path %></li>
	      <!--
	      <% if user_signed_in? %>
	      	<li><%= link_to "ACCOUNT SETTINGS", edit_user_registration_path %></li>
          <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
         <% end %>
       	-->
	    </ul>
	  </div><!-- /.navbar-collapse -->
	</div><!-- /.container -->
</nav>

app/views/layouts/_socialshare.html.erb
<% ref_url = "http://dailywatercooler.com/?ref=" + @info.fetch("data")[0].fetch("id") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="input-group">
      <div class="input-group-addon">
        <span class="fa fa-link"></span> <small>Link</small>
      </div>
      <input type="text" class="form-control" value=<%= ref_url %> >
    </div>
    <div>
      <table class="table borderless">
        <tbody>
          <tr>
            <td>
              <a class="btn btn-default" href="#" role="button" data-toggle="modal" data-target="#myModal"><i class="fa fa-envelope"></i> <small>Email</small></a>
            </td>
            <td>
              <% ref_facebook = "https://www.facebook.com/sharer/sharer.php?u=" + ref_url %>
              <a class="btn btn-default" href=<%= ref_facebook %> target="_blank"><i class="fa fa-facebook"></i> <small>Share</small></a>
            </td>
            <td>
              <% ref_twitter = "https://twitter.com/intent/tweet?text=Do+you+read+%40the_dwc%3F+Get+a+morning+email+jam-packed+with+news+and+humor+to+make+sure+you're+never+left+behind%3A&url=http%3A%2F%2Fdailywatercooler.com%2F%3Fref%3D"+@info.fetch("data")[0].fetch("id") %>
              <% ref_twttr_pop = "window.open('print.html', 'newwindow', 'width=300, height=250'); return false;" %>
              <a class="btn btn-default" href=<%= ref_twitter %> target="_blank" ><i class="fa fa-twitter"></i> <small>Tweet</small></a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- MODAL -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title cabin" id="myModalLabel">EMAIL A FRIEND</h4>
      </div>
      <div class="modal-body">
        <div align="center">
          <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
            <%= f.input :name, label: 'What your name?', :required => true %>
            <%= f.input :to_email, label: 'Enter in a single email', :required => true %>
            <% ref_email = "I signed up for the best morning newsletter and want you to sign up too. Free delicious news delivered to you daily. Sign up with this link to get started: "+ref_url %>
            <%= f.input :message, :as => :text, :required => true , :input_html => { :rows => 6, value: ref_email } %>
            <div class= "hidden">
              <%= f.input :from_email, label: 'What is your email?', :required => true, :input_html => { value: params[:search] } %>
              <%= f.input :nickname, :hint => 'Leave this field blank!' %>
            </div>
            <div>
              </br>
              <%= f.button :submit, 'REFER FRIENDS', :class=> "btn btn-default" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END MODAL -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Daily Water Cooler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag %>
  <script src="js/bootstrap.min.js"></script>
  <script src="//load.sumome.com/" data-sumo-site-id="9b4b4b06d7c8a11e66141fa075be53836b74029203c85cfe04be05a17f0c137e" async></script>
  <link href='//fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <meta property="og:site_name" content="The Daily Water Cooler" />
  <meta property="og:title" content="The Daily Water Cooler" />
  <meta property="og:url" content="http://www.dailywatercooler.com" />
  <meta property="og:image" content="http://www.dailywatercooler.com/assets/fb_thumbnail-f00749d31f80de40f37ad878b8258750.jpg"/>
  <meta property="og:description" content="The Daily Water Cooler is a curated email newsletter delivered every weekday morning designed to inform and delight. Takes only a moment each day to make sure you don't miss out on what people are talking about. Subscribe today." />
  <meta name="google-site-verification" content="oGn032rdRZoBzlWd9cCihuKa6xMf2yFXY2gOxsNRK4o" />
</head>
<body>
	<div id="wrap">
		<%=render 'layouts/header' %>
		<%-# <div class="container"> -%>
			<%= yield %>
		<%-# </div> -%>
		<div id="push"></div>
	</div>
	<%= render 'layouts/footer' %>

	<%= render 'layouts/ga' if Rails.env.production? %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Daily Water Cooler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag %>
  <script src="//load.sumome.com/" data-sumo-site-id="9b4b4b06d7c8a11e66141fa075be53836b74029203c85cfe04be05a17f0c137e" async></script>
</head>
<body>
	<div id="wrap">
		<%= render 'layouts/header' %>
		<%-# <div class="container"> -%>
			<%= yield %>
		<%-# </div> -%>
		<div id="push"></div>
	</div>
	<%= render 'layouts/footer' %>

	<%= render 'layouts/ga' if Rails.env.production? %>

</body>
</html>